_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

limit_train_batches: 20000
val_check_interval: 1000

strategy: ddp_find_unused_parameters_true
accelerator: gpu
devices: 2
num_nodes: 1
sync_batchnorm: true
deterministic: false