name: catsbench
channels:
  - conda-forge
  - defaults
dependencies:
  - click==8.2.1
  - einops=0.8.1
  - hydra-core=1.3.2
  - hydra-submitit-launcher=1.2.0
  - jupyter=1.1.1
  - lightning=2.5.2
  - pip=25.1.1
  - pot=0.9.5
  - python=3.12
  - rich=14.0.0
  - scikit-learn=1.7.0
  - seaborn=0.13.2
  - torch-ema=0.3.0
  - transformers=4.52.4
  - pip:
    - --index-url https://download.pytorch.org/whl/cu124
    - torch==2.6.0
    - torchvision==0.21.0
    - --index-url https://pypi.org/simple
    - flash-attn==2.7.3 
    - torch-fidelity==0.3.0
    - pqm==0.6.3
    - comet_ml==3.49.12