# @package hydra

job:
  chdir: false
run:
  dir: ${paths.log_dir}/runs/${hydra:runtime.choices.data}/${hydra:runtime.choices.method}/${hydra:runtime.choices.experiment}/${seed}/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/runs/${hydra:runtime.choices.data}/${hydra:runtime.choices.method}/${hydra:runtime.choices.experiment}/${seed}/${now:%Y-%m-%d}_${now:%H-%M-%S}
job_logging:
  handlers:
    file:
      filename: ${hydra:runtime.output_dir}/${task_name}.log