_target_: src.methods.models.unet.UNet 
img_size: 32 
num_categories: ${data.num_categories}
in_channels: 3
num_channels: 64
num_layers: 2 
ch_mults: [1, 2, 2, 2]
attention_resolution: 16
num_groups: 32
num_att_heads: 4
dropout: 0.1