_target_: src.methods.cnot.CNOT

pi_optimizer:
  _target_: torch.optim.Adam
  _partial_: true # may be 1e-4 too
  betas: [0.5, 0.999]

f_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  betas: [0.5, 0.999]

prior: ${prior}

dim: ${data.dim}
num_categories: ${data.num_categories}
epsilon: 1
pi_layers: [512, 512, 512, 512]
f_layers: [512, 512, 512, 512] 
f_emb_dim: ???
num_timesteps: ${prior.num_timesteps}, 
pi_iters: 10 


