_target_: src.methods.cnot.CNOT

pi_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3 # may be 1e-4 too
  betas: [0.5, 0.999]

f_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  betas: [0.5, 0.999]

prior: ${prior}

dim: ${data.dim}
num_categories: ${data.num_categories}
epsilon: 1
pi_layers: [256, 256, 256, 256]
f_layers: [64, 64, 64, 64] 
f_emb_dim: 64
num_timesteps: ${prior.num_timesteps}, 
lambda_reg: 10
pi_iters: 10 


