_target_: src.methods.csbm_ar.CSBM_AR

model: ${model}

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0004
  betas: [0.95, 0.99]

ema:
  _target_: torch_ema.ExponentialMovingAverage 
  _partial_: true
  decay: 0.999

prior: ${prior}

num_first_iterations: 10
kl_loss_coeff: 1.0
ce_loss_coeff: 1.0
mse_loss_coeff: 0
gradient_accumulation_steps: 1
gradient_clip_val: null
use_mini_batch: false
ignore_index: -100