_target_: src.methods.dlight_sb_m.DLightSB_M

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  betas: [0.95, 0.99]

prior: ${prior}

dim: ${data.dim}
num_potentials: 10
distr_init: uniform
