_target_: src.methods.dlight_sb_m.DLightSB_M

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  betas: [0.95, 0.99]

prior: ${prior}

dim: ${data.dim}
num_potentials: 10
kl_loss_coeff: 1.0
mse_loss_coeff: 0.0
use_mini_batch: false
distr_init: uniform
