_target_: src.methods.dlight_sb.DLightSB

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-2
  betas: [0.95, 0.99]

prior: ${prior}

dim: ${data.dim}
num_potentials: 10
distr_init: uniform
