_target_: src.methods.light_sb_d.LightSB_D

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0004
  betas: [0.95, 0.99]

prior: ${prior}

dim: ${data.dim}
num_potentials: 10
distr_init: uniform
