metric_callback:
  _target_: src.utils.BenchmarkImagesLogger
  dim: ${data.dim}
  input_shape: ${data.input_shape}
  num_categories: ${data.num_categories}
  num_samples: 100 # number of samples to visualize
  num_trajectories: 4
  num_translations: 2