metric_callback:
  _target_: src.metrics.BenchmarkHDGMetricsCallback
  dim: ${data.dim}
  num_categories: ${data.num_categories}
  num_timesteps: ${prior.num_timesteps}
  num_cond_samples: 1000
  train_test_split: 0.8
  classifier_lr: 1e-2

plotter_callback:
  _target_: src.plotter.BenchmarkHDGPlotterCallback
  dim: ${data.dim}
  num_categories: ${data.num_categories}
  num_samples: 2048 # number of samples to visualizeZ
  num_trajectories: 4
  num_translations: 3
  axlim:
    - -100
    - 100