metric_callback:
  _target_: src.utils.BenchmarkLogger
  dim: ${data.dim}
  num_categories: ${data.num_categories}
  num_samples: 2048 # number of samples to visualize
  num_cond_samples: 1000
  num_trajectories: 4
  num_translations: 3
  axlim:
    - -100
    - 100