metric_callback:
  _target_: src.utils.BenchmarkLogger
  dim: ${data.dim}
  num_categories: ${data.num_categories}
  num_cond_samples: 1000
  num_refs: 100
  re_tessellation: null
  permute_tests: null
  kernel: "hamming"
  num_trajectories: 4
  num_translations: 3
  axlim:
    - -100
    - 100