metric_callback:
  _target_: src.metrics.BenchmarkImageMetricsCallback
  dim: ${data.dim}
  num_categories: ${data.num_categories}
  train_test_split: 0.8
  classifier_lr: 1e-2

plotter_callback:
  _target_: src.plotter.BenchmarkImagePlotterCallback
  dim: ${data.dim}
  input_shape: ${data.input_shape}
  num_categories: ${data.num_categories}
  num_samples: 4 # number of samples to visualize
  num_trajectories: 4
  num_translations: 2
