model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: epoch_{epoch:03d}
  every_n_epochs: 1
  monitor: null 
  verbose: false
  save_last: True
  save_top_k: -1
  mode: min
  auto_insert_metric_name: false
  save_weights_only: false
