defaults:
  - data: benchmark_images
  - prior: default
  - model: unet
  - method: csbm
  - callbacks: [rich_progress_bar, model_summary, model_checkpoint, benchmark_images_metrics]
  - logger: tensorboard
  - trainer: multi_gpu
  - experiment: null
  - hydra: default
  - _self_

paths:
  root_dir: .
  data_dir: ${paths.root_dir}/data
  ckpt_dir: ${paths.root_dir}/checkpoints
  log_dir: ${paths.root_dir}/logs
  output_dir: ${hydra:runtime.output_dir}

task_name: train
seed: 42
ckpt_path: null # for resuming the training or testing
