defaults:
  - data: toy
  - prior: default
  - model: simple_mlp 
  - method: csbm
  - callbacks: [rich_progress_bar, model_summary, toy_metric]
  - logger: comet
  - trainer: gpu
  - experiment: null
  - hydra: default
  - override hydra/launcher: slurm
  - _self_

paths:
  root_dir: .
  data_dir: ${paths.root_dir}/data
  ckpt_dir: ${paths.root_dir}/checkpoints
  log_dir: ${paths.root_dir}/logs
  output_dir: ${hydra:runtime.output_dir}

task_name: train
seed: 42
ckpt_path: null # for resuming the training or testing
