defaults:
  - data: gaussian_to_swiss_roll
  - prior: default
  - model: simple_mlp 
  - method: csbm
  - callbacks: [rich_progress_bar, model_summary, toy_metric_callback]
  - logger: wandb
  - trainer: gpu
  - experiment: null
  - _self_

paths:
  root_dir: .
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}

task_name: train
seed: 42
ckpt_path: null # for resuming the training or testing

hydra:
  run:
    dir: ${paths.log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${paths.log_dir}/${task_name}/multirun/${now:%Y-%m-%d_%H-%M-%S}
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${task_name}.log
