# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: ais-gpu
gpus_per_node: 1
cpus_per_task: 1
tasks_per_node: 1
nodes: 1
timeout_min: 23040  # 16 days
name: ${task_name}-${hydra:runtime.choices.data}
array_parallelism: 8
setup:
  - source activate dot_bench
