# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: gpu_dev
gpus_per_node: 1
cpus_per_task: 1
tasks_per_node: 1
nodes: 1
timeout_min: 720 # 12 hours
name: ${task_name}-${hydra:runtime.choices.data}
array_parallelism: 2
setup:
  - source activate dot_bench
